<?php

namespace Database\Factories;

use App\Models\MonthlyBill;
use App\Models\Payment;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class PaymentFactory extends Factory
{
    protected $model = Payment::class;

    public function definition(): array
    {
        return [
            'monthly_bill_id' => MonthlyBill::factory(),
            'payment_date' => fake()->date(),
            'amount' => fake()->randomFloat(2, 50000, 500000),
            'payment_method' => fake()->randomElement(['cash', 'transfer', 'qris', 'virtual_account']),
            'reference_number' => null, // auto-generated by boot event
            'verified_by' => null,
            'notes' => fake()->optional()->sentence(),
        ];
    }

    public function verified(): static
    {
        return $this->state(fn (array $attrs) => [
            'verified_by' => User::factory(),
        ]);
    }
}
